export enum NumberConstants {
  BEST_PLAYERS_NUMBER = 10,
  X4_CURD_NUMBER = 16,
  X6_CURD_NUMBER = 36,
  X8_CURD_NUMBER = 64,
  RANDOM_COF = 0.5,
  IMG_NUMBER = 8,
  FIRST_X6_IMG_SET = 32,
  FIRST_SCORE_COF = 100,
  SECOND_SCORE_COF = 10,
  SECOND_IN_MINUTE = 60,
}
